### ISSUE TITLE
v1.0.0 bug合集

### ISSUE THREAD

**Issue by BrotherJing** [kitauji-gwent/kitauji-gwent#19]
- [x] 排行榜乱序
- [x] 打leader牌没有重置计时器
- [x] 阵容切换年级无法保存 
- [x] 大号君和指导老师无法出牌
- [x] 特殊牌需要限制数量
- [x] 切换阵容中立卡数量增加

**Comment by everfate** [comment]
大号夫妇吃加藤和指导老师的buff只能加到20，久一年2，理应加到40吧。

**Comment by BrotherJing** [comment]
@everfate 噢 那个不能叠加的
