### ISSUE TITLE
交易BUG

### ISSUE THREAD

**Issue by Void-zack** [kitauji-gwent/kitauji-gwent#28]
卖牌的时候左侧全部牌组里的牌会随机自己跳回到当前阵容里，应该是个BUG吧

**Comment by Void-zack** [comment]
貌似是因为牌太少的缘故，牌多起来了之后就没有这个问题了

**Comment by BrotherJing** [comment]
@Void-zack 可能是因为修改了阵容没点确认就切到部费tab了。因为不能卖当前阵容里的牌，所以这种情况会跳回去，没问题
