### ISSUE TITLE
运行 node server/server.js 时报错，SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by zebra38324** [kitauji-gwent/kitauji-gwent#56]
看起来是语法错误，还是说我缺少了某些必要的依赖库吗
报错信息：
D:\2020.8\kitauji\kitauji-gwent\server\dao\db.js:37
  async addUser(user) {
        ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\2020.8\kitauji\kitauji-gwent\server\server.js:7:10)
    at Module._compile (module.js:571:32)

**Comment by pzhlkj6612** [comment]
你好。

你的 node 是什么版本的？试试 `node --harmony-async-await server/server.js` ？

**Comment by zebra38324** [comment]
> 你好。
> 
> 你的 node 是什么版本的？试试 `node --harmony-async-await server/server.js` ？

你好，我的node是7.5.0的，跟readme里推荐的一样。
用了你说的命令之后确实可以运行了
请问这样的信息显示是正常的吗：
![image](https://user-images.githubusercontent.com/43290696/107348964-a195fc80-6b02-11eb-9607-61719f0978dc.png)

这时再去用浏览器访问http://localhost:3000，提示“Cannot GET /”
另外，如果我想要在本地调试代码的话，是不是需要在config里面设置一个我自己的服务器？
非常感谢您的帮助

**Comment by zebra38324** [comment]
> 你好。
> 
> 你的 node 是什么版本的？试试 `node --harmony-async-await server/server.js` ？

图片好像显示不出来，运行node --harmony-async-await server/server.js之后的提示信息：
Please visit http://localhost:3000 to start playing
请用浏览器访问 http://localhost:3000 开始游戏（麻烦大家看到这句话，不要再来问我本地版怎么打开了（捂脸 ））
(node:21164) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Database not started. But you can still connect to online servers
本地未安装数据库，请忽略报错并在游戏中选择线上服务器。>_<

**Comment by pzhlkj6612** [comment]
> 提示“Cannot GET /”

**Comment by pzhlkj6612** [comment]
> 请问这样的信息显示是正常的吗

正常。

> 本地未安装数据库，请忽略报错并在游戏中选择线上服务器。>_<

它的意思是，程序没有在本地找到 MongoDB ，因此无法储存用户和对局数据，但没有这些数据就无法进行游戏，所以你需要连接到远程服务器。

**Comment by pzhlkj6612** [comment]
@zebra38324 如何，有进展了吗？

**Comment by zebra38324** [comment]
> @zebra38324 如何，有进展了吗？
不是很顺利，运行`npm run build -- --production` 会报错：

D:\2020.8\kitauji-gwent>npm run build -- --production

> kitauji-gwent@1.0.0 build D:\2020.8\kitauji-gwent
> gulp --production "--production"

D:\2020.8\kitauji-gwent\gulpfile.js:185
);
^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireOrImport (D:\2020.8\kitauji-gwent\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11)
    at execute (D:\2020.8\kitauji-gwent\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js:37:3)

npm ERR! Windows_NT 10.0.18362
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "--" "--production"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! kitauji-gwent@1.0.0 build: `gulp --production "--production"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kitauji-gwent@1.0.0 build script 'gulp --production "--production"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kitauji-gwent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --production "--production"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kitauji-gwent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kitauji-gwent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\2020.8\kitauji-gwent\npm-debug.log

无论是否带上--production 参数，都会报错。看起来似乎是我的gulp出现了问题，但是一直没有头绪
之前的版本中我直接运行`npm run build` 命令是没有问题的，不过现在好像是已经修改了脚本文件

**Comment by pzhlkj6612** [comment]
现在你的本地仓库停留在哪一个 commit ？

**Comment by zebra38324** [comment]
> 现在你的本地仓库停留在哪一个 commit ？

我刚刚拉取了最新的commit，仍然会报一样的错
```
commit 12da562b74a6053fd8b9fc01c94e826e7d84e452 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: brotherjing <yang_ji@worksap.co.jp>
Date:   Thu Feb 11 19:17:07 2021 +0800

    update readme
```

**Comment by pzhlkj6612** [comment]
我刚才读了 [gulpfile.js](https://github.com/kitauji-gwent/kitauji-gwent/blob/12da562b74a6053fd8b9fc01c94e826e7d84e452/gulpfile.js#L180-L190) ，发现这边的方法调用看着有些奇怪。你试试这么改：

```diff
  var sassTaskDelegate = gulp.series(
    abilitySpritesGenerationTask,
    kyoaniThemeResizeTask,
    kyoaniThemeSpriteTask,
-   sassTask,
+   sassTask
  );
  var cardSpritesGenerationTaskDelegate = gulp.series(
    resizeTask,
-   cardSpritesGenerationTask,
+   cardSpritesGenerationTask
  );
```

**Comment by zebra38324** [comment]
> 我刚才读了 [gulpfile.js](https://github.com/kitauji-gwent/kitauji-gwent/blob/12da562b74a6053fd8b9fc01c94e826e7d84e452/gulpfile.js#L180-L190) ，发现这边的方法调用看着有些奇怪。你试试这么改：

原来是这里多了逗号，我按照你说的改了一下，其他的地方仍然有报错，看起来是gulp-jimp-wrapper库的导入出了问题：
```
D:\2020.8\kitauji-gwent>npm run build -- --production

> kitauji-gwent@1.0.0 build D:\2020.8\kitauji-gwent
> gulp --production "--production"

D:\2020.8\kitauji-gwent\node_modules\gulp-jimp-wrapper\dist\index.js:27
const processImage = async (img, cb, MIMEType) => {
                           ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\2020.8\kitauji-gwent\gulpfile.js:19:12)
    at Module._compile (module.js:571:32)
```

**Comment by pzhlkj6612** [comment]
这跟之前关于 `async` 的报错应该是同一件事，即当前的 node 并不（默认）支持 `async/await` 。我怀疑我引入 gulp-jimp-wrapper 时并没有使用 node 7.5.0 进行测试，所以在那时我并没有遇到这个错误。你试试 7.6.0 。

**Comment by pzhlkj6612** [comment]
另外，你似乎可以直接使用 [`npm run build`](https://github.com/kitauji-gwent/kitauji-gwent/blob/12da562b74a6053fd8b9fc01c94e826e7d84e452/package.json#L45) ，而不需要带参数 `--production` 。我之前一直用的 `npm run gulp` ，所以需要手动传参。

给你带来了困扰，抱歉。

**Comment by zebra38324** [comment]
> 另外，你似乎可以直接使用 [`npm run build`](https://github.com/kitauji-gwent/kitauji-gwent/blob/12da562b74a6053fd8b9fc01c94e826e7d84e452/package.json#L45) ，而不需要带参数 `--production` 。我之前一直用的 `npm run gulp` ，所以需要手动传参。
> 
> 给你带来了困扰，抱歉。

我刚刚又看了一遍才发现，推荐的node版本已经改成了11.1.0，是我的问题，非常抱歉。
另外，[client/scss/main.scss](https://github.com/kitauji-gwent/kitauji-gwent/blob/master/client/scss/main.scss )文件中，第18行`@import "../../public/build/kyoani"` 会提示找不到对应文件，将此行注释后我已经可以成功运行了，暂时还没发现有什么问题
非常感谢你的帮助

**Comment by pzhlkj6612** [comment]
> 第18行`@import "../../public/build/kyoani"` 会提示找不到对应文件

好的，之后修。

> 推荐的node版本已经改成了11.1.0，是我的问题

不，这并不是你的问题，是我之前折腾依赖的时候忘记修改文档了。你有时间的话可以看看提交记录。

---

对之前的问题的简单解释：

### 为何用 node 7.5.0 会在 async 处出错

- [async function - JavaScript | MDN § Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#browser_compatibility)

你可以使用 `npm run build -- --harmony-async-await` 启用这个特性（但是这并不代表你能够使用 node 7.5.0 构建本项目。当然，有时间的话你可以继续做尝试）。

### 为何用 node -le 7 会在方法调用末尾的逗号处出错

- "Trailing comma in functions" in [Trailing commas - JavaScript | MDN § Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#browser_compatibility)
- [Node.js ES2015/ES6, ES2016 and ES2017 support § trailing commas in function syntax](https://node.green/#ES2017-features-trailing-commas-in-function-syntax)

### 在低版本 node 你可能还会遇到什么问题

- "Spread in object literals" in [Spread syntax (...) - JavaScript | MDN § Trailing commas - JavaScript | MDN § Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#browser_compatibility)

**Comment by zebra38324** [comment]
@pzhlkj6612 我再继续慢慢学习，非常感谢你的帮助

**Comment by pzhlkj6612** [comment]
> 第18行`@import "../../public/build/kyoani"` 会提示找不到对应文件

@zebra38324 你好！ #43 合了，你再试试？

**Comment by zebra38324** [comment]
> @zebra38324 你好！ #43 合了，你再试试？

我试了一下，已经可以成功运行了，谢谢
