### ISSUE TITLE
dalao有测试群吗？

### ISSUE THREAD

**Issue by hzsydy** [kitauji-gwent/kitauji-gwent#7]
试玩了一下最新版，感觉黄前十六年卡组比黄前十五年强不少（

**Comment by BrotherJing** [comment]
居然已经开始玩了🤣 还没正式发布呐
这里有个汇总，其实都差不多，各有特色
https://docs.qq.com/sheet/DSE5LQkhaR1dPemdP
群还没有 之后应该会建一个

**Comment by hzsydy** [comment]
啊 看起来十五年的卡组还没施工完毕的样子 太急切了23333
（想加大佬好友x）

**Comment by hzsydy** [comment]
话说突然发现dalao的头像莫不是乒乓的smile（
