### ISSUE TITLE
加部友惠阵亡之后，其对同一列成员的加成似乎没有消失？

### ISSUE THREAD

**Issue by hzsydy** [kitauji-gwent/kitauji-gwent#8]
![image](https://user-images.githubusercontent.com/9162943/82978673-21029080-9fb3-11ea-9a9d-7ee0841ddf64.png)

**Comment by hzsydy** [comment]
如图，大号夫妇的战力是28，感觉应该是bug？

**Comment by BrotherJing** [comment]
是设计成这样的。还有投掷类的技能，这些加成可以叠加，还可以诱饵换下来继续用

**Comment by hzsydy** [comment]
惊了 所以能上若干次获得若干层号角加成吗

**Comment by BrotherJing** [comment]
号角和士气不能 这两个是巫师原版的技能
送礼物和投掷参考了巫师之昆特牌，相当于一次性的攻击和加成（不知道怎么解释🤣 你细品

**Comment by hzsydy** [comment]
I see, commandersHorn是一个卡的状态而不是一个数字加成

**Comment by BrotherJing** [comment]
刚才图没出来 以为你说的是久一年技能🤦 那确实是个bug得修
